base_path: data
glove_source_path: /home/jiangqn/datasets/embeddings/glove.840B.300d.txt
embed_size: 300
hidden_size: 600
num_layers: 4
dropout: 0.5
weight_tying: False
batch_size: 64
lr: 0.0003
weight_decay: 0
epoches: 5
eval_freq: 100
clip_grad_norm: 5.0